AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This CloudFormation template creates a role assumed by CloudFormation
  during CRUDL operations to mutate resources on behalf of the customer.

Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      MaxSessionDuration: 8400
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: resources.cloudformation.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:SourceAccount:
                  Ref: AWS::AccountId
              StringLike:
                aws:SourceArn:
                  Fn::Sub: arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:type/resource/AWS-RolesAnywhere-TrustAnchor/*
      Path: "/"
      Policies:
        - PolicyName: ResourceTypePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                - "acm-pca:GetCertificateAuthorityCertificate"
                - "iam:CreateServiceLinkedRole"
                - "rolesanywhere:CreateTrustAnchor"
                - "rolesanywhere:DeleteTrustAnchor"
                - "rolesanywhere:DisableTrustAnchor"
                - "rolesanywhere:EnableTrustAnchor"
                - "rolesanywhere:GetTrustAnchor"
                - "rolesanywhere:ListTagsForResource"
                - "rolesanywhere:ListTrustAnchors"
                - "rolesanywhere:TagResource"
                - "rolesanywhere:UntagResource"
                - "rolesanywhere:UpdateTrustAnchor"
                Resource: "*"
Outputs:
  ExecutionRoleArn:
    Value:
      Fn::GetAtt: ExecutionRole.Arn
